[workspace] 
channels = [
    "pytorch",
    "https://conda.rosettacommons.org",
    "dglteam/label/cu118",
    "conda-forge",
    "nvidia",
    "pyg",
]

platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies] 
rf_diffusion_all_atom = { path = "." }

[package] 
name = "rf_diffusion_all_atom"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.3.*" }
